FROM openjdk:8

RUN apt update

WORKDIR /opt

COPY ./fuseki.zip /opt/fuseki.zip

RUN unzip -qq fuseki.zip

RUN mv apache-* jena-fuseki/

WORKDIR /opt/jena-fuseki/

COPY ./app/modules/request/ontology.owl /opt/jena-fuseki/ontology.owl

CMD ["/opt/jena-fuseki/fuseki-server", "--file=/opt/jena-fuseki/ontology.owl", "/MasterThesisDS18"]
